# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u8bbe\u5907\u4f9b\u5e94\u5546', max_length=50, verbose_name='\u8bbe\u5907\u4f9b\u5e94\u5546')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u4f9b\u5e94\u5546',
            },
        ),
    ]
