# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '\u8bbe\u5907\u4f9b\u5e94\u5546', 'verbose_name_plural': '\u8bbe\u5907\u4f9b\u5e94\u5546'},
        ),
        migrations.AddField(
            model_name='device',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='\u8bbe\u5907\u4f9b\u5e94\u5546', null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Supplier', verbose_name='\u8bbe\u5907\u4f9b\u5e94\u5546'),
        ),
    ]
