# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180126_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
