# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180126_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, help_text='\u662f\u5426\u5df2\u5220\u9664', verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('contact_name', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u4eba', max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_phone', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u7535\u8bdd', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('name', models.CharField(help_text='\u5ba2\u6237\u540d\u79f0', max_length=50, null=True, verbose_name='\u5ba2\u6237\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237',
                'verbose_name_plural': '\u5ba2\u6237',
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, help_text='\u662f\u5426\u5df2\u5220\u9664', verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('contact_name', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u4eba', max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_phone', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u7535\u8bdd', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('name', models.CharField(help_text='\u5546\u52a1\u5904\u540d\u79f0', max_length=50, verbose_name='\u5546\u52a1\u5904\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5546\u52a1\u5904',
                'verbose_name_plural': '\u5546\u52a1\u5904',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, help_text='\u662f\u5426\u5df2\u5220\u9664', verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('contact_name', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u4eba', max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_phone', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u7535\u8bdd', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('name', models.CharField(help_text='\u7ecf\u9500\u5546\u540d\u79f0', max_length=50, verbose_name='\u7ecf\u9500\u5546\u540d\u79f0')),
                ('short_name', models.CharField(help_text='\u7ecf\u9500\u5546\u7b80\u79f0', max_length=50, verbose_name='\u7ecf\u9500\u5546\u7b80\u79f0')),
                ('dealer_number', models.CharField(help_text='\u7ecf\u9500\u5546\u7f16\u53f7', max_length=50, verbose_name='\u7ecf\u9500\u5546\u7f16\u53f7')),
                ('commercials', models.ManyToManyField(help_text='\u5546\u52a1\u5904', to='polls.Commercial', verbose_name='\u5546\u52a1\u5904')),
            ],
            options={
                'verbose_name': '\u7ecf\u9500\u5546',
                'verbose_name_plural': '\u7ecf\u9500\u5546',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, help_text='\u662f\u5426\u5df2\u5220\u9664', verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('contact_name', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u4eba', max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_phone', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u7535\u8bdd', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('name', models.CharField(help_text='\u4e8b\u4e1a\u90e8\u540d\u79f0', max_length=50, verbose_name='\u4e8b\u4e1a\u90e8\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4e8b\u4e1a\u90e8',
                'verbose_name_plural': '\u4e8b\u4e1a\u90e8',
            },
        ),
        migrations.CreateModel(
            name='MainFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, help_text='\u662f\u5426\u5df2\u5220\u9664', verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('contact_name', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u4eba', max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_phone', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u7535\u8bdd', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('name', models.CharField(help_text='\u4e3b\u673a\u5382\u540d\u79f0', max_length=50, verbose_name='\u4e3b\u673a\u5382\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u5382',
                'verbose_name_plural': '\u4e3b\u673a\u5382',
            },
        ),
        migrations.CreateModel(
            name='PlatformCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, help_text='\u662f\u5426\u5df2\u5220\u9664', verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('contact_name', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u4eba', max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_phone', models.CharField(blank=True, default=b'', help_text='\u8054\u7cfb\u7535\u8bdd', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('name', models.CharField(help_text='\u516c\u53f8\u540d\u79f0', max_length=50, verbose_name='\u516c\u53f8\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u603b\u5e73\u53f0\u516c\u53f8',
                'verbose_name_plural': '\u603b\u5e73\u53f0\u516c\u53f8',
            },
        ),
        migrations.AddField(
            model_name='mainfactory',
            name='platform_company',
            field=models.ForeignKey(blank=True, help_text='\u5e73\u53f0\u516c\u53f8', null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.PlatformCompany', verbose_name='\u5e73\u53f0\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='division',
            name='main_factory',
            field=models.ForeignKey(blank=True, help_text='\u4e3b\u673a\u5382', null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.MainFactory', verbose_name='\u4e3b\u673a\u5382'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='division',
            field=models.ForeignKey(blank=True, help_text='\u4e8b\u4e1a\u90e8', null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Division', verbose_name='\u4e8b\u4e1a\u90e8'),
        ),
        migrations.AddField(
            model_name='client',
            name='dealers',
            field=models.ManyToManyField(help_text='\u7ecf\u9500\u5546', to='polls.Dealer', verbose_name='\u7ecf\u9500\u5546'),
        ),
        migrations.AddField(
            model_name='device',
            name='client_owner',
            field=models.ForeignKey(blank=True, help_text='\u6240\u5c5e\u5927\u5ba2\u6237', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_devices', to='polls.Client', verbose_name='\u6240\u5c5e\u5927\u5ba2\u6237'),
        ),
        migrations.AddField(
            model_name='device',
            name='holder',
            field=models.ForeignKey(blank=True, help_text='\u8bbe\u5907\u6301\u6709\u8005', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holde_devices', to='polls.Dealer', verbose_name='\u8bbe\u5907\u6301\u6709\u8005'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='\u6240\u5c5e\u7ecf\u9500\u5546', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_devices', to='polls.Dealer', verbose_name='\u6240\u5c5e\u7ecf\u9500\u5546'),
        ),
    ]
