# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180126_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '\u8bbe\u5907\u4fe1\u606f', 'verbose_name_plural': '\u8bbe\u5907\u4fe1\u606f'},
        ),
    ]
