# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180131_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot_type', models.CharField(choices=[('main_depot', '\u603b\u5e93\u5e93\u623f'), ('dealer_depot', '\u7ecf\u9500\u5546\u5e93\u623f')], default='main_depot', help_text='\u5e93\u623f\u7c7b\u578b', max_length=15, verbose_name='\u5e93\u623f\u7c7b\u578b')),
                ('name', models.CharField(help_text='\u5e93\u623f\u540d\u79f0', max_length=50, verbose_name='\u5e93\u623f\u540d\u79f0')),
                ('dealer', models.ForeignKey(blank=True, help_text='\u6240\u5c5e\u7ecf\u9500\u5546', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Dealer', verbose_name='\u6240\u5c5e\u7ecf\u9500\u5546')),
            ],
            options={
                'verbose_name': '\u5e93\u623f',
                'verbose_name_plural': '\u5e93\u623f',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='depot',
            field=models.ForeignKey(blank=True, help_text='\u5e93\u623f', null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Depot', verbose_name='\u5e93\u623f'),
        ),
    ]
