# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180201_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='is_destory',
            new_name='is_destoryed',
        ),
    ]
