# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-02 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180201_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='minotor_status',
            new_name='monitor_status',
        ),
    ]
