# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-22 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_auto_20180202_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, help_text='\u662f\u5426\u5df2\u5220\u9664', verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('object_id', models.PositiveIntegerField()),
                ('rank', models.CharField(choices=[('platform_company', '\u603b\u5e73\u53f0\u516c\u53f8'), ('main_factory', '\u4e3b\u673a\u5382'), ('disivion', '\u4e8b\u4e1a\u90e8'), ('commercial', '\u5546\u52a1\u5904'), ('dealer', '\u7ecf\u9500\u5546'), ('major', '\u5927\u5ba2\u6237')], help_text='\u5c42\u7ea7', max_length=20, verbose_name='\u5c42\u7ea7')),
                ('role', models.CharField(choices=[('super_admin', '\u8d85\u7ea7\u7ba1\u7406\u5458'), ('admin', '\u7ba1\u7406\u5458'), ('worker', '\u4e1a\u52a1\u5458'), ('warekeeper', '\u4ed3\u5e93\u7ba1\u7406\u5458')], help_text='\u89d2\u8272', max_length=20, verbose_name='\u89d2\u8272')),
                ('phone', models.CharField(help_text='\u7535\u8bdd', max_length=20, verbose_name='\u7535\u8bdd')),
                ('name', models.CharField(help_text='\u59d3\u540d', max_length=20, verbose_name='\u59d3\u540d')),
                ('phone_verified', models.BooleanField(default=False, help_text='\u7535\u8bdd\u662f\u5426\u5df2\u9a8c\u8bc1', verbose_name='\u7535\u8bdd\u662f\u5426\u5df2\u9a8c\u8bc1')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('depot', models.ForeignKey(blank=True, help_text='\u8d1f\u8d23\u4ed3\u5e93', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depot_keepers', to='polls.Depot', verbose_name='\u8d1f\u8d23\u4ed3\u5e93')),
                ('user', models.OneToOneField(help_text='\u7528\u6237', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u4e2a\u4eba\u4fe1\u606f',
                'verbose_name_plural': '\u4e2a\u4eba\u4fe1\u606f',
            },
        ),
    ]
